version: "3"
services:
  vue0app:
    mem_limit: 4g
    container_name: vue0app
    image: vue0app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=production
      - BROWSERLESS=ws://localhost:3001
      - NUXT_OPENAI_API_BASEURL=https://172.22.16.5:5002/v1
      - NUXT_PUBLIC_DISABLE_LOGIN=true
    volumes:
      - .:/app
    command: ["node", "/app/.output/server/index.mjs"]
  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chrome
    restart: always
    ports:
      - 3001:3000