version: "3"
services:
  vue0app:
    mem_limit: 4g
    container_name: vue0app
    image: vue0app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - BROWSERLESS=ws://localhost:3001
      - NUXT_OPENAI_API_BASEURL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - NUXT_PUBLIC_DISABLE_LOGIN=true
    volumes:
      - ./sqlite:/app/sqlite
    command: ["node", "/app/.output/server/index.mjs"]
  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chrome
    restart: always
    ports:
      - 3001:3000